### ISSUE TITLE
No permite agregar cuenta Gmail de Google Suite 

### ISSUE THREAD

**Issue by CarlosRebolledo** [Oxygem/Kanmail#101]
No he podido probar Kanmail porque no puedo agregar mi cuenta Gmail de Google Suite

**Comment by Fizzadar** [comment]
Hi @CarlosRebolledo! (using Google translate):

¿Has echado un vistazo al [documento de proveedores para Gmail](https://github.com/Oxygem/Kanmail/blob/master/docs/providers.md#gmail--gsuite)? Es posible que deba habilitar IMAP (o su administrador puede tener que hacerlo).

> Have you had a look at the [providers doc for Gmail](https://github.com/Oxygem/Kanmail/blob/master/docs/providers.md#gmail--gsuite)? You may need to enable IMAP (or your admin may have to).
