### ISSUE TITLE
Index out of range when initial batches >1

### ISSUE THREAD

**Issue by Fizzadar** [Oxygem/Kanmail#104]
See: https://github.com/Oxygem/Kanmail/issues/89#issuecomment-622926696

**Comment by KKPMW** [comment]
@Fizzadar Just update on this issue - I started getting the same error even with batch=1 now. And this is only for that mailbox which had an authentication issue. Not sure how those two are related, but the outcome is that Kanmail isn't fetching emails from it. Other mailboxes appear to work well.

If you will want to test this yourself, feel free to use the details of the account I sent to you. I will try to adjust various settings on my own too.

**Comment by Fizzadar** [comment]
@KKPMW this should now be fixed in the latest (`v1.2005071756`) release!

The issue was with parsing the bodystructure IMAP response, fixed by https://github.com/Oxygem/Kanmail/commit/62ad745c2b1fc67c9416b4c4532d25bf070726d3.

**Comment by KKPMW** [comment]
Most excellent news, it works now. Thanks a lot @Fizzadar
