### ISSUE TITLE
Random hangs on Linux

### ISSUE THREAD

**Issue by kappa** [Oxygem/Kanmail#110]
The UI freezes about 50% when I try to paste my password from clipboard with Ctrl-V. Debian Buster.

**Comment by Fizzadar** [comment]
I've now got a proper Linux dev machine to test for this issue! We have made progress on [Linux compatibility](https://github.com/Oxygem/Kanmail/blob/master/docs/linux.md) but unfortunately Debian is still an issue.

I'm going to try on Debian buster to see if I can replicate the hang (and identify if Kanmail works on Buster).

**Comment by Fizzadar** [comment]
@kappa I have failed to replicate this. When it freezes does it later recover or require killing the process?
