### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by KKPMW** [Oxygem/Kanmail#119]
**Describe the bug**

Today I jumped on a new bug: a certain error about UTF-8 characters prevents emails being fetch from the inbox.

**Screenshots**

![Screenshot 2020-05-11 at 10 44 18 AM](https://user-images.githubusercontent.com/7273684/81536539-69476f00-9374-11ea-8f9d-cbfc6ebda60d.png)

**Additional context**

I can see, by opening the same inbox via a browser client, that it has a certain weird character in the senders name:

![Screenshot 2020-05-11 at 10 46 25 AM](https://user-images.githubusercontent.com/7273684/81536761-bcb9bd00-9374-11ea-838b-42fc94df0637.png)

It was spam. The error disappeared when I deleted that message using the web browser client.

**Comment by Fizzadar** [comment]
@KKPMW would it be possible to get the full traceback from the error overlay? 

Sidenote: I've added an issue [to add copy+paste ability to errors for issue logs](https://github.com/Oxygem/Kanmail/issues/120).

**Comment by KKPMW** [comment]
@Fizzadar a bit too late now, already deleted the message. Maybe we can postpone this issue and if it repeats again - I will update it with a full log.

**Comment by Fizzadar** [comment]
@KKPMW the latest release, `v1.2005140926`, _should_ fix this as all string decoding is now handled (more) safely.
