### ISSUE TITLE
License activation not working

### ISSUE THREAD

**Issue by Areontar** [Oxygem/Kanmail#121]
**Describe the bug**
After purchasing a license, the activation errors out; Button turns to "Error Saving license: undefined"

**Screenshots**

**Additional context**
URL: http://localhost:56881/api/license
ErrorName: undefined
ErrorMessage: undefined
Kanmail version: 1.2005140926
Status: 400
null

**Comment by Fizzadar** [comment]
Hi @Areontar! This is no good - does the license button disappear when you re-open the app? And which OS/version are you running?

I have tried and failed to replicate this on any OS. If possible would you mind running Kanmail from a terminal? It should output a full traceback.

**Comment by Areontar** [comment]
Hi,
Running on osx catalina 10.15.4
![Screen Shot 2020-05-15 at 11 34 20](https://user-images.githubusercontent.com/2413363/82084502-3d8ff600-96a0-11ea-9dde-ae89bc7c8986.png)

terminal only prints this:
```
[INFO] 127.0.0.1 - - [15/May/2020 11:35:22] "GET /open-window?url=%2Flicense&unique_key=license&title=Kanmail+License&width=540&height=320 HTTP/1.1" 204 -
[INFO] 127.0.0.1 - - [15/May/2020 11:35:22] "GET /license?window_id=bef8f830-6050-45ff-beb9-6469c13bbf46 HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [15/May/2020 11:35:22] "GET /api/settings HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [15/May/2020 11:35:30] "POST /api/license HTTP/1.1" 400 -
```

is there a flag to run in debug?

**Comment by Fizzadar** [comment]
I believe I've figured this out! The key has to contain both the email + token emailed to you, so there should be two lines in there. Clearly the error here is useless, which I will fix!

Will also review the license key email too to make this clear.

**Comment by Areontar** [comment]
That worked, thanks!
