### ISSUE TITLE
[macOS Catalina] Kanmail Shows Blank Screen after Launch

### ISSUE THREAD

**Issue by spaghett1c0de** [Oxygem/Kanmail#123]
I'm using macOS Catalina version 10.15.4. Kanmail shows a blank screen after launch.

<img width="1512" alt="Screen Shot 2020-05-28 at 7 44 16 PM" src="https://user-images.githubusercontent.com/18053491/83215520-0566c980-a11c-11ea-975a-04c89ec97c60.png">

Any ideas? 🤔

Best,
Vincent

**Comment by Fizzadar** [comment]
Hi Vincent! This looks v.odd; is this a fresh download of Kanmail? Would you be able to run it from terminal and dump the output here (assuming standard install `/Applications/Kanmail.app/Contents/MacOS/Kanmail`)?

It looks like the JS bundle hasn't loaded for whatever reason, but it should absolutely be there!

**Comment by spaghett1c0de** [comment]
@Fizzadar 
Thanks for getting back to me! It is a fresh download of Kanmail from the official site. I ran it through the terminal and got this 👇 
```
/Applications/Kanmail.app/Contents/MacOS/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
 * Serving Flask app "Kanmail" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO] 127.0.0.1 - - [29/May/2020 02:46:11] "GET /ping HTTP/1.1" 200 -
[ERROR] 127.0.0.1 - - [29/May/2020 02:46:12] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x960\x11ÜVõ\x8cô®¢>owöë¨ev¿+]\x0f&\x8b±Ó')
[INFO] 127.0.0.1 - - [29/May/2020 02:46:12] "ü0ÜVõô®¢>owöë¨ev¿+]&±Ó" HTTPStatus.BAD_REQUEST -
[ERROR] 127.0.0.1 - - [29/May/2020 02:46:12] code 400, message Bad request version ('òE')
[INFO] 127.0.0.1 - - [29/May/2020 02:46:12] "üiæe¬Zêñ Ð	ø³AÖ·nàOèníëÿT7 òE" HTTPStatus.BAD_REQUEST -
[ERROR] 127.0.0.1 - - [29/May/2020 02:46:12] code 400, message Bad request version ('Kï7ê1°Ì\x95\x00\x00\x14À')
[INFO] 127.0.0.1 - - [29/May/2020 02:46:12] "£NÅVw°_?#o	u3ºùÞ Kï7ê1°ÌÀ" HTTPStatus.BAD_REQUEST -
```

**Comment by Fizzadar** [comment]
@spaghett1c0de I'm not sure what's happening here! Due to the unicode I'm thinking this could be a locale issue, could you run + paste the output of `locale` here?

Additionally, if you run via the terminal with `KANMAIL_DEBUG=on ...` it might give more information. The next release will also print out (when debug enabled) the server token + port, meaning you'll be able to open the app in Firefox/similar to test where the issue lies (will update the support doc with this info).
