### ISSUE TITLE
Sizing of new column textbox too small

### ISSUE THREAD

**Issue by Flapadar** [Oxygem/Kanmail#124]
**Describe the bug**
At 1920x1080, the new column textbox is too short, and only displays "Colum" rather than "Column name..."

This can be reproduced in the pywebview app and in Chrome.

**Screenshots**
![image](https://user-images.githubusercontent.com/5580429/83291534-63f57b80-a1e0-11ea-8e2a-518e95c04f07.png)

**Comment by Fizzadar** [comment]
Now fixed/released in `v1.2008071409`!
