### ISSUE TITLE
Unicode support for SMTP uasernames/passwords

### ISSUE THREAD

**Issue by mazlo** [Oxygem/Kanmail#125]
**Describe the bug**
I am getting the below error message when trying to add a new account. The error message has to do with my password propably.. I am using a special character 'ü'.

![image](https://user-images.githubusercontent.com/221185/83965289-de925b00-a8b2-11ea-8b48-aef71cee8b39.png)

**Additional context**
I have a keyboard with german layout and used a special character in my password.

**Comment by Fizzadar** [comment]
Thanks for the report @mazlo! I've fixed IMAP unicode compatability in https://github.com/Oxygem/Kanmail/commit/cc88d52b5adb5428be017f5b19c16b240c4ac1f5, which will be included in the next release (likely tonight/tomorrow morning).

Unfortunately if you're using the same username/password for SMTP this is a bug in Python itself!, see: https://bugs.python.org/issue29750. There's no real workaround currently so I'm keeping track of updates there. I can potentially patch the Python implementation, but need to investigate whether that will  build correctly with pyinstaller.

**Comment by Fizzadar** [comment]
The latest release, `v1.2006081025`, now includes the IMAP fix!

**Comment by Fizzadar** [comment]
The latest release includes full support for this!
