### ISSUE TITLE
STARTTLS extension not supported by server.

### ISSUE THREAD

**Issue by hamedzurat** [Oxygem/Kanmail#136]
**Describe the bug**
error : *STARTTLS extension not supported by server.*

**Screenshots**
![dsafdsafdsafsafsafsa](https://user-images.githubusercontent.com/38398613/87877043-d115d800-c9fd-11ea-8cfc-aa273d5c8933.PNG)

**Additional context**
after this problem 
https://github.com/Oxygem/Kanmail/issues/94

i turned on this 
https://myaccount.google.com/lesssecureapps

but now **kanmail** is showing me **STARTTLS extension not supported by server.**

**Comment by hamedzurat** [comment]
ok found out something 
if I turn on **TLS** then it makes that error
but in
 https://support.google.com/mail/answer/7126229
they said to turn on it if it's possible

**Comment by Fizzadar** [comment]
@hamedzurat I think the choice here is _either_ SSL or TLS - the Google docs don't make this very obvious! 

For SMTP I think you can either do port 465 + SSL OR port 587 + TLS (no SSL). There's no need to use both SSL + TLS so either works :)

For reference I currently use SSL + on port 465 for my gmail accounts.

**Comment by hamedzurat** [comment]
but is there any way to make it secure ??
I mean, Google has become very paranoid about my security :)

**Comment by Fizzadar** [comment]
Either one should be suitably secure - I'd recommend TLS over SSL (per https://www.sparkpost.com/resources/email-explained/ssl-tls-starttls-encyption/).

It is possible to do both at the same time - but Gmail does not appear to support this, so one has to choose!
