### ISSUE TITLE
Is there a team option

### ISSUE THREAD

**Issue by nicolastyles** [Oxygem/Kanmail#141]
I am trying to find out if Kanmail has a team option. 
I would like to assign, chat, etc with my team.

**Comment by Fizzadar** [comment]
Hi @nicolastyles currently we've not got any plans for team based features although I'd be interested to hear what  you think these might look like. Is this a shared inbox kind of situation?

**Comment by Fizzadar** [comment]
Closing as this won’t be implemented.
