### ISSUE TITLE
Can't connect outlook

### ISSUE THREAD

**Issue by jet10000** [Oxygem/Kanmail#142]
![image](https://user-images.githubusercontent.com/2258120/95624945-40a1dd80-0aaa-11eb-9379-ba00ddb1a520.png)

**Comment by Fizzadar** [comment]
Hi @jet10000! The account settings UI should display more information on the actual error - could you add a screenshot of that here so I can investigate further?

The 400 indicates either a missing setting or invalid user/password combo for IMAP or SMTP - this is potentially a result of autoconfiguration.

**Comment by jet10000** [comment]
![image](https://user-images.githubusercontent.com/2258120/95652371-00327600-0b23-11eb-9306-cc9044d38843.png)

**Comment by Fizzadar** [comment]
Please could you double check your username & password; this error means the server rejected the login (but connected fine) so either the email or password must be incorrect.

**Comment by jet10000** [comment]
Thanks!
