### ISSUE TITLE
attach files errors

### ISSUE THREAD

**Issue by jet10000** [Oxygem/Kanmail#143]
![image](https://user-images.githubusercontent.com/2258120/95653901-9750fb00-0b2e-11eb-99e1-c0dbaa7e5adf.png)

**Comment by Fizzadar** [comment]
Hi @jet10000, thank you for the bug report this looks like a issue when running inside Docker, I'll update this once fixed!

**Comment by Fizzadar** [comment]
@jet10000 this is now fixed in the latest release [`v1.2010161619`](https://github.com/Oxygem/Kanmail/releases/tag/v1.2010161619) (commit https://github.com/Oxygem/Kanmail/commit/b76edd9772c421c70716bbab7a6605925d1887e5).

**Comment by jet10000** [comment]
> @jet10000 this is now fixed in the latest release [`v1.2010161619`](https://github.com/Oxygem/Kanmail/releases/tag/v1.2010161619) (commit [b76edd9](https://github.com/Oxygem/Kanmail/commit/b76edd9772c421c70716bbab7a6605925d1887e5)).

ok, Please update docker hub.

**Comment by Fizzadar** [comment]
The tag is pushed to the hub @ https://hub.docker.com/r/fizzadar/kanmail/tags!
