### ISSUE TITLE
IMAP folder names for German users

### ISSUE THREAD

**Issue by georks** [Oxygem/Kanmail#146]
**Describe the feature you'd like**
The software should automatically recognise German folder names.
For example: 
"sent" is "Gesendet" in German.
"archive" is "Archiv"
"trash" is"Papierkorb"

**Additional context**
I am happy to help you with a German translation of folder names

**Comment by Fizzadar** [comment]
I really want to implement this - these folders should be picked up currently in that Kanmail will map the "archive" folder to the "archiv" IMAP folder. Assuming this works then the key here is translating the Kanmail interface which I am very keen on doing.

@georks if you could provide translations for each folder that would be amazing; I'm hoping to look into this next week.

**Comment by georks** [comment]
Here are some translations for (hopefully) all the main IMAP-folders. If something is missing, please let me know.

# IMAP foldernames English - German

| English | German |
|-----|-----|
| INBOX | Posteingang |
| | INBOX |
| outbox | Postausgang |
| sent | Gesendet |
| |  gesendet |
| archive | Archiv |
| | Archivieren |
| drafts | Entwuerfe |
| | Entwürfe |
| templates | Vorlagen |
| | Templates |
| junk, spam | Junk |
| | Spam |
| | Unerwünscht |
| | Unerwuenscht |
| snooze | Zurueckgestellt |
| | Zurückgestellt |
| trash | Papierkorb |
| | Gelöschte Elemente |
| notes | Notizen |

**Comment by Fizzadar** [comment]
@georks thank you very much for sending those through. The underlying issue comes from another library in use here, I've patched the detection in https://github.com/Oxygem/Kanmail/commit/9f462c24d5cdc3506bbd1eed99c77936ef16ad8a using the translations provided. Do you have any recommended German email provider? I'd like to test this before building a release!

**Comment by georks** [comment]
@Fizzadar glad, I could be of help.
As far as I understand the patch, you are using some kind of i18n for translations, or? 
I was thinking in the same direction. To use i18n for translations into different languages, rather than renaming the folder names.

German providers for (basic) free e-mail accounts are for example:

www.gmx.de
www.web.de
www.mail.de
www.freenet.de
... and other...

**Comment by Fizzadar** [comment]
Thank you for sending those, I'll get a test account setup.

Yes we're doing a mapping for the main email folders (inbox, sent, archive, drafts, trash & spam) - so under each account there's a "mailboxes" tab which lets you set these - and the PR addition should now automatically pick them up when configuring new accounts.

This is a temporary workaround while we build out a proper i18n for the whole app, as I'd like full support for translations of interface language in addition to email folder suppor.

**Comment by Fizzadar** [comment]
Closing this now as done and have added https://github.com/Oxygem/Kanmail/issues/152 to track the wider i18n implementation.
