### ISSUE TITLE
Failed to execute main script - on windows 10

### ISSUE THREAD

**Issue by nickbe** [Oxygem/Kanmail#154]
When starting kanmail.exe this error message is all I get:
"Failed to execute main script". 

Do need to install a different python version first? If so, then this will make lot's of problem
if there's already a python version installed on windows?

**Comment by Fizzadar** [comment]
Hi @nickbe! I managed to track this down to an issue running on Windows when  the new webview2 is installed; I've now fixed that and released an updated Windows client that should fix this issue: https://updates.kanmail.io/Kanmail-win-1.2103140902.zip.

**Comment by nickbe** [comment]
Yep. Now it works. Thanks and I'm really curious about kanmail now :)

**Comment by Fizzadar** [comment]
That's great to hear @nickbe; thank you for testing that out!

**Comment by nickbe** [comment]
One other question though: Where do you move the mails exactly on moving them around in the kanboard? (Do you just mark them or move them to subfolders? if so how are they named and where?)

**Comment by Fizzadar** [comment]
They're moved into the relevant folders (these are created on demand if needed). They have the exact name as the column  so they should be visible in any other email client/web interface.

There's also a feature to enable copying messages into other folders, which works with gmail-style labels (ie the email becomes part of both the inbox and other folder).

Re: draft/sent folders - which email provider are you using and what do the mailbox settings look like (settinngs -> accounts -> mailboxes)? Kanmail should automatcally pick up the correct folders represnting drafts/sent mail, but this is specific to each provider so is possibly not working as expected for you.

**Comment by nickbe** [comment]
Found them yes (forgot to mount the new folder names). We're using a Univention/OX server. Strangely enough not folder names were automatically selected at all in the Mailboxes section:

![image](https://user-images.githubusercontent.com/10890765/111082531-18128980-8509-11eb-993a-a23c3e9cfeb2.png)
