### ISSUE TITLE
Where are folders created right now

### ISSUE THREAD

**Issue by nickbe** [Oxygem/Kanmail#161]
Where do you move the mails exactly when moving them around in the kanboard? (Do you just mark them or move them to subfolders? if so how are those folders named and where?)

Also it seems that Sent, Draft and so on are not related to the standard mailbox folders.
Sorry for asking but I want to know exactly what is happening.

**Comment by Fizzadar** [comment]
Hi @nickbe! Emails are moved to folders matching the names of the kanbanboard columns, if a folder doesn't exist Kanmail will simply create it.

I believe the issue with sent/draft mailboxs is the same as #160.

**Comment by nickbe** [comment]
Yes, thanks anyway. It's clear now ;-)
