### ISSUE TITLE
Cannot add an account to kanmal at all right now

### ISSUE THREAD

**Issue by nickbe** [Oxygem/Kanmail#166]
I've just downloaded the latest windows build. Kanmail starts but now it's not possible to add any account at all. Login data is valid - I've checked with other mail clients, just to make sure.

Can anyone confirm that this is a problem with the current version?

**Comment by Fizzadar** [comment]
Hi @nickbe! I just tested on Windows using the latest build (from 18 days ago) but adding an account worked OK; if you could provide some more info I'm sure we can figure this out!:

- What is happening when you try to add an account? (any screenshots would be super helpful)
- Do any errors show up on the page? 
- What email provider are you trying to setup wiith?

**Comment by nickbe** [comment]
I just found the problem. If I fill out the first 3 fields and then click on the advanced settings to add server and so on, then the setup routine seems not to work. But if I skip the first setup screen completely and jump directly to the advanced mail settings.... it works.

**Comment by Fizzadar** [comment]
That's really helpful, I will try to replicate this situation! To cofirm - do any errors appear when trying to add the account in the first instance?

**Comment by nickbe** [comment]
no nothing. I just filled out the fields and then clicked the advanced configuration.

**Comment by Fizzadar** [comment]
Hi @nickbe; I'm currently working on a new version of the interface for adding new accounts which is delaying fixing this. Expecting to have that released either today or tomorrow which should fix the issue for you!

**Comment by Fizzadar** [comment]
Update on this: release went out last thing on Friday and should fix this issue!

**Comment by nickbe** [comment]
Thx

**Comment by edeast** [comment]
Hello, on version 1.2104091748

I can't add a custom email account, after clicking the Custom IMAP/SMTP the pop up screen closes before I  can do anything. 
Was able to catch a kanmail is loading screen. 
![image](https://user-images.githubusercontent.com/4231398/118697313-29b03000-b7dd-11eb-892a-971368098221.png)

**Comment by edeast** [comment]
I was able to add an account, after clicking "Add a different account" rather than clicking the "Custom IMAP/SMTP" then modifying the settings after.

**Comment by Fizzadar** [comment]
@edeast thank you for the update, that's v.helpful - I will try to replicate this on my Windows test machine!
