### ISSUE TITLE
Signatures

### ISSUE THREAD

**Issue by Fizzadar** [Oxygem/Kanmail#169]
+ signatures settings (generic, not attached to any account)
+ per account default signature
+ per alias default signature?

**Comment by HammyHavoc** [comment]
Is this possible? It's a major feature, especially being able to add formatting like bolding and hyperlinks.

**Comment by Fizzadar** [comment]
Definitely possible - this is likely to be the next major chunk of work for me on Kanmail

**Comment by Fizzadar** [comment]
This is now implemented and live in the latest release 🎉!
