### ISSUE TITLE
Allow Kanmail to work with Protonmail Bridge

### ISSUE THREAD

**Issue by edeast** [Oxygem/Kanmail#171]
**Describe the feature you'd like**

I can connect a protonmail account to kanmail via the bridge, but cannot see incoming messages in kanmail.
error is 503  fetch failed: list message build: wrong section 1.

![image](https://user-images.githubusercontent.com/4231398/118710283-13f63700-b7ec-11eb-9ec1-5d9361baf499.png)

It is possible to send messages from kanmail.  

**Additional context**
I have tried many combinations of settings. 
 If I Use SSL, i get the Wrong_Version_Number, so need to keep SSL disabled.
Outgoing TLS seams to work fine.

**Comment by Fizzadar** [comment]
Hi @edeast thank you for this report; I'm going to setup a test protonmail account to check why this isn't working properly!

**Comment by edeast** [comment]
The inbox is working now, thank you.

**Comment by Fizzadar** [comment]
@edeast thank you for confirming that! I suspect this [this change](https://github.com/Oxygem/Kanmail/commit/f8763a7dc61995719a20a0e86aa7b7141fce3431) fixed it by accident :) I was still working on getting hold of a premium account to test with!

**Comment by ar4sdoteth** [comment]
SSL: WRONG_VERSION_NUMBER wrong version number (_ssl.c:1131), 

@edeast - how did you manage to get proton mail working with the bridge? (is it still working?)

if I can get this up and running I'd be happy to buy a license
