### ISSUE TITLE
Tag latest docker image on build (Can‘t use docker)

### ISSUE THREAD

**Issue by Emmanuel-true** [Oxygem/Kanmail#177]
**Describe the bug**
Using default tag: latest
Error response from daemon: manifest for fizzadar/kanmail:latest not found: manifest unknown: manifest unknown

**Screenshots**
![Screenshot 2021-07-24 144246](https://user-images.githubusercontent.com/26563556/126870286-a8143a47-25dd-4f91-875b-8d2e6f5e4c2e.jpg)

**Additional context**
I just can't install it use docker

**Comment by Fizzadar** [comment]
Hi @Emmanuel-true - we don't currently tag the `latest` version, so you'll need to specify the version number; the most recent docker image is: `docker pull fizzadar/kanmail:1.2104091748`.

I'm going to leave this open to track starting to tag latest, as it makes it simpler to get setup.

**Comment by Fizzadar** [comment]
This is now fixed and the `latest` tag exists and is updated with new releases.
