### ISSUE TITLE
Broken Contact Delete button

### ISSUE THREAD

**Issue by HammyHavoc** [Oxygem/Kanmail#185]
![image](https://user-images.githubusercontent.com/503951/130760628-9ba36ca3-3c34-4bdc-a6cb-7067de43e4ca.png)
When you click the Delete button, you can't actually read what it changes to on Windows.

**Comment by Fizzadar** [comment]
Thank you for spotting this, will get it corrected!

**Comment by Fizzadar** [comment]
This is now fixed as of the latest release!
