### ISSUE TITLE
Failed to execute main script

### ISSUE THREAD

**Issue by georks** [Oxygem/Kanmail#192]
**Describe the bug**
Kanmail v1.2110040834
Windows 10 German language, up to date with updates

Starting Kanmail.exe ends up in an error window: "Failed to execute main script"
After that, you can find in the task-manager 2 running processes of Kanmail.exe.

So, I restarted the machine, tried it again with the same result: First the error, then the 2 running processes.

The previous Version of Kanmail worked without this error. Where can I find the previous version again?

**Comment by Fizzadar** [comment]
I released a fix for this last night in [`v1.2110131703`](https://github.com/Oxygem/Kanmail/releases/tag/v1.2110131703). Turned out to be a dodgy requirements file which I am now setting up automated tests to catch such issues going forward. Thank you once again for raising this @georks!
