### ISSUE TITLE
Unable to "Complete adding account" (Gsuite) on macOS 12.1

### ISSUE THREAD

**Issue by ar4sdoteth** [Oxygem/Kanmail#195]
As the title says, I'm able to go through the auth in the browser successfully and land back in Kanmail to fill out Account name/email send address/Name to send from, but clicking `Complete adding` account doesn't action anything. 

Macbook Pro M1
Just upgraded to Monterey and didn't have kanmail installed previously :(

**Comment by Fizzadar** [comment]
Hi @ar4sdoteth, thank you for spotting & reporting this; I've just pushed `v1.2112242054` which fixes this issue (bad import, fixed commit: https://github.com/Oxygem/Kanmail/commit/28aa47e5bd603e1ccbb1bef01cf552f43c6ba8c3).
