### ISSUE TITLE
Docker - Not able to get /settings or /license page : "Invalid session token provided!"

### ISSUE THREAD

**Issue by matbgn** [Oxygem/Kanmail#200]
**Describe the bug**
I'm not able to get to the http://localhost:4420/license and http://localhost:4420/settings

**Screenshots**
![image](https://user-images.githubusercontent.com/13169819/156199395-5a04fd58-6211-4f36-8044-2aac46f60cce.png)

**Additional context**
Just a fresh docker install run with :

     docker run -p 4420:4420 -v /home/matbgn/kanmail:/home/kanmail/.config/kanmail/ --name kanmail   fizzadar/kanmail:1.2112242054

Any advice ?

**Comment by matbgn** [comment]
Naturally it could be a missconfiguration of the session token, but any hint on how to properly achieve it, will be appreciated ;-)

**Comment by Fizzadar** [comment]
Nice catch, @matbgn! The token really exists to prevent the desktop "app" being accessed via browser/prevent CSRF-style attacks. Quickest fix is probably to simply add the session token to the URL when opening other windows in Docker mode. I will check but I think this is how the compose window works..

**Comment by Fizzadar** [comment]
Massively delayed on getting this fixed; fix now released in `v1.2205081824`.
