### ISSUE TITLE
Docker Pull isn't working

### ISSUE THREAD

**Issue by omennemo** [Oxygem/Kanmail#79]
On attempting to install via docker I am facing the below error:

Error response from daemon: manifest for fizzadar/kanmail:latest not found: manifest unknown: manifest unknown

**Comment by Lerentis** [comment]
@omennemo have a look at the docker hub to find out which tags are available: https://hub.docker.com/r/fizzadar/kanmail/tags

**Comment by omennemo** [comment]
Got it. I am running it for the wrong architecture. Thanks!
