### ISSUE TITLE
Investigate: add notes/points/metadata to emails

### ISSUE THREAD

**Issue by Fizzadar** [Oxygem/Kanmail#84]
How to represent this on the server (IMAP) side to maintain consistency between clients. Ideally without negatively affecting other email clients!

**Comment by lucasverra** [comment]
there is no much alternative here, and it must be clear for the project. there is no doubt gmail proprietary non standard API is great. It adds tons of features that IMAP/SMTP protocols will probably never have. 

I'm comfortable with both since standard email protocols are worth investing on.

**Comment by Fizzadar** [comment]
Agreed. Kanmail is designed to be a general email client and not rely on the GMail/proprietary APIs. Going to close this as, without significant hacking/abuse of the IMAP protocol this simply isn't feasible.

May revisit in the future!
