### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)

### ISSUE THREAD

**Issue by gerroon** [Oxygem/Kanmail#91]
Hi

I setup the docker container and I am trying to add my email server. When I try to add an account I get the error in the title in the settin gs page and I do not see any other info in the Docker terminal.

**Comment by Fizzadar** [comment]
@gerroon which email provider is this? Will probably need to setup a test account to check this.

**Comment by KKPMW** [comment]
I had this same issue with my universities email account. No way to set up a test in this case, but it uses Microsoft's exchange mail, if that helps.

**Comment by gerroon** [comment]
@Fizzadar it is a paid email service I only have a one paid account that I use, I got it through Namecheap.

**Comment by Fizzadar** [comment]
@gerroon what settings are you using with Namecheap? I can connect OK (no account but get to authentication and fail) with these settings ([from here](https://www.namecheap.com/support/knowledgebase/article.aspx/1179/2175/general-private-email-configuration-for-mail-clients-and-mobile-devices)):

<img width="643" alt="Screenshot 2020-05-01 at 10 05 16" src="https://user-images.githubusercontent.com/1026154/80795031-4efedb80-8b93-11ea-9748-f659ef3cb2df.png">

**Comment by gerroon** [comment]
Hi

Are you trying it with Docker, that is the only working setup for me, which is the one giving me this error.

I am using those server settings however my email adress is through my own domain. IMAP:993, SMTP:587

I also do not have "Verify SSL hostname" in the Incoming server pane. I am also not sure if this error is related to SMTP or IMAP or both. 

Please bear in mind that these settings work perfectly in Mailpile or couple other Android email apps.

**Comment by Fizzadar** [comment]
@gerroon I will test with Docker ASAP! Will confirm here once done so. The verify checkbox is from the latest release (as of last night).

(Also going to fix the highlighting of whether an issue is IMAP or SMTP).

**Comment by Fizzadar** [comment]
I've just tested this in Docker and is working as above (giving auth failed).

Looking elsewhere online it seems `WRONG_VERSION_NUMBER` would point to using a non-SSL port, but `993` is definitely correct.

@gerroon could you try with the latest release? (it will also give better error output).
