### ISSUE TITLE
"The setting you are looking for is not available for your account" (App Password)

### ISSUE THREAD

**Issue by steveharman** [Oxygem/Kanmail#93]
We use Gmail inside Google G-Suite.  I tried adding a mail account into Kanmail and after authenticating with Google they informed me "_The setting you are looking for is not available for your account_"

Does this mean Kanmail doesn't / can't support G-Suite or is there perhaps something that needs enabling in our Google Apps / G-Suite to provide app passwords?

Thanks

**Comment by KKPMW** [comment]
For me the "app password" only appeared after enabling two-step verification. Did you try that?

**Comment by stewartmckee** [comment]
Here is the docs for "Sign in using App Passwords".  Seems you do need to enable 2-step verification. 
[https://support.google.com/accounts/answer/185833?hl=en](https://support.google.com/accounts/answer/185833?hl=en)

**Comment by Fizzadar** [comment]
Yes 2 factor should fix this; I'll update the providers doc to reflect this.

**Comment by Fizzadar** [comment]
Docs have been updated to reflect this @ https://github.com/Oxygem/Kanmail/commit/97cbae5d5442773d27b2e632e89200d106462bb5
