### ISSUE TITLE
GMAIL - b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

### ISSUE THREAD

**Issue by pixelforests** [Oxygem/Kanmail#94]
After entering login details for gmail and using the app password the following error is displayed

b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

**Comment by Fizzadar** [comment]
@pixelforests would you be able to test using the same credentials and another email client to confirm? Unsure any other way to debug this.

**Comment by menjilx** [comment]
![image](https://user-images.githubusercontent.com/14908836/80550104-89c90e00-89f1-11ea-84d8-0d4ef1617a02.png)

Yes, got same error!

**Comment by Fizzadar** [comment]
@menjilx does this also happen in other email clients?

Another thing to check - is IMAP enabled within Gmail? I'm not sure it is by default (https://support.google.com/mail/answer/7126229?hl=en&visit_id=637237486805908327-3689613495&rd=2).

**Comment by pixelforests** [comment]
> 
> 
> @pixelforests would you be able to test using the same credentials and another email client to confirm? Unsure any other way to debug this.

Will try later this week.



> 
> 
> @menjilx does this also happen in other email clients?
> 
> Another thing to check - is IMAP enabled within Gmail? I'm not sure it is by default (https://support.google.com/mail/answer/7126229?hl=en&visit_id=637237486805908327-3689613495&rd=2).

@Fizzadar I confirmed IMAP was enabled for my side in Gmail (it is not by default), issue still occurs.

**Comment by hamedzurat** [comment]
https://github.com/Foundry376/Mailspring
and 
https://www.thunderbird.net/en-US/

is working but Kanmail is not

**Comment by hamedzurat** [comment]
> After entering login details for gmail and using the app password the following error is displayed
> 
> b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'


goto https://myaccount.google.com/lesssecureapps
and turnon it
