### ISSUE TITLE
Contacts - Unique constraint failed

### ISSUE THREAD

**Issue by zoljargalg** [Oxygem/Kanmail#97]
Below error happened during initial contacts sync & app crashed.

I believe there's unhandled exception caused by sqlite.

---

sqlite3.IntegrityError: UNIQUE constraint failed: contacts.email, contacts.name

---

Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1246, in _execute_context
  File "sqlalchemy/engine/default.py", line 588, in do_execute
sqlite3.IntegrityError: UNIQUE constraint failed: contacts.email, contacts.name

**Comment by Fizzadar** [comment]
This should now be properly handled by the `v1.2004301944` release, which includes proper error handling for contacts.
