### ISSUE TITLE
`Failed to execute script pyi_rth_certifi` when start

### ISSUE THREAD

**Issue by ericxsun** [Oxygem/Kanmail#98]
kanmail: v1.2004231151
mac: 10.13.6
when start kanmail 
```
Kanmail.app/Contents/MacOS/Kanmail
```
an error occurs
```
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_certifi.py", line 13, in <module>
  File "/Users/nick/.pyenv/versions/3.7.6/envs/kanmail-3.7/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "ssl.py", line 98, in <module>
ImportError: dlopen(/Users/myName/Applications/Kanmail.app/Contents/MacOS/_ssl.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/qinluo/Applications/Kanmail.app/Contents/MacOS/libcrypto.1.1.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/myName/Applications/Kanmail.app/Contents/MacOS/libcrypto.1.1.dylib
[82956] Failed to execute script pyi_rth_certifi
```

**Comment by Fizzadar** [comment]
So this is due to the build occurring on 10.15, and `pyinstaller` can't fix this as per https://pyinstaller.readthedocs.io/en/stable/usage.html#making-mac-os-x-apps-forward-compatible. 

I'm looking into options, one is to build using a VM and older version of MacOS.

**Comment by Fizzadar** [comment]
Possible solution to test: https://gist.github.com/phfaist/a5b8a895b003822df5397731f4673042

**Comment by ericxsun** [comment]
> Possible solution to test: https://gist.github.com/phfaist/a5b8a895b003822df5397731f4673042

Could you release one ? It'll be very nice.

**Comment by Fizzadar** [comment]
@ericxsun the latest build, `v1.2004301944`, should now work for you! Built using the `10.12` SDK and tested working in a `10.13.6` VM.

**Comment by maxwolf9731** [comment]
Ciao, same problem here with a 10.11.16 macos. If it is not a big probleme can you compile also for me :)
Thanks

**Comment by Fizzadar** [comment]
@maxwolf9731 unfortunately I can't get it working - I can't get pyobj to compile using the older SDKs :/ 10.12 will have to be the oldest supported MacOS for now.

**Comment by ericxsun** [comment]
> @ericxsun the latest build, `v1.2004301944`, should now work for you! Built using the `10.12` SDK and tested working in a `10.13.6` VM.

Thanks so much. Nice job

**Comment by Fizzadar** [comment]
@maxwolf9731 change of plan! I managed to get the 10.10 SDK setup and the latest release should now be compatible.

I don't have any way to test or verify this though, if you could let me know if it works that would be excellent.
