### ISSUE TITLE
see no way to set any imap options like server/port

### ISSUE THREAD

**Issue by darenr** [Oxygem/Kanmail#99]
Trying to add account to a regular imap/smtp email and the add account doesn't let me set any options that I can find?

**Comment by Fizzadar** [comment]
@darenr if you add the name/email/password with any details it will then attempt to autoconf, fail and drop into the full IMAP/SMTP setup.

To make this simpler, there should be a way/button to bypass the autoconfig.

**Comment by darenr** [comment]
you mean when I click add account the button just goes grey but nothing ever happens after that, I click save and am told to create an account again. Can I force drop into the IMAP set up in anyway?

**Comment by Fizzadar** [comment]
Yes that should work. I've just tried locally using `test` for the name + email + password and it has worked ("Could not autoconfigure") and opens the IMAP/SMTP settings, that might work?

Currently it's not possible to force it any other way; I'm going to add a button for this.

**Comment by darenr** [comment]
I never see "Could not autoconfigure" - should I just wait longer? What's the timeout please?

**Comment by Fizzadar** [comment]
With `test` in all the fields it should be a few seconds. What OS/version are you using Kanmail on? It could be specific.

**Comment by darenr** [comment]
Mac (I waited 60 seconds and nothing) - latest Mac OSX, behind a proxy if that's relevant?

**Comment by Fizzadar** [comment]
I'm also on latest Mac so unlikely to be that! Would you mind running Kanmail from terminal to see if there's any errors (normally `/Applications/Kanmail.app/Contents/MacOS/Kanmail`).

If not I believe this could be a JS error, which currently aren't shown outside of the main window; I've added https://github.com/Oxygem/Kanmail/issues/100 to track this (will hopefully be in a release this week).

**Comment by darenr** [comment]
```(base) drace-mac:~ drace$ /Applications/Kanmail.app/Contents/MacOS/Kanmail
/Applications/Kanmail.app/Contents/MacOS/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
2020-04-29T11:39:52 WARNING Waiting for main window: HTTPConnectionPool(host='localhost', port=4420): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d06a890>: Failed to establish a new connection: [Errno 61] Connection refused'))
2020-04-29T11:39:52 WARNING Waiting for main window: HTTPConnectionPool(host='localhost', port=4420): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d086610>: Failed to establish a new connection: [Errno 61] Connection refused'))
2020-04-29T11:39:52 WARNING Waiting for main window: HTTPConnectionPool(host='localhost', port=4420): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dbe8710>: Failed to establish a new connection: [Errno 61] Connection refused'))
 * Serving Flask app "kanmail" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO]  * Running on http://127.0.0.1:4420/ (Press CTRL+C to quit)
[INFO] 127.0.0.1 - - [29/Apr/2020 11:39:52] "GET /api/ping HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [29/Apr/2020 11:39:54] "GET /?window_id=f224f594-22a8-433e-a593-96e2e32a3cc1 HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [29/Apr/2020 11:39:54] "GET /api/settings HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [29/Apr/2020 11:39:56] "GET /open-window?url=%2Fsettings&unique_key=settings&title=Kanmail+Settings&width=800&height=800 HTTP/1.1" 204 -
[INFO] 127.0.0.1 - - [29/Apr/2020 11:39:56] "GET /settings?window_id=fac33271-8c7b-4618-b164-02b0df17d175 HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [29/Apr/2020 11:39:57] "GET /api/settings HTTP/1.1" 200 -

```

**Comment by darenr** [comment]
I don't see any js errors, can I run in debug mode?

**Comment by darenr** [comment]
tracked it down - needed to set proxy up for it

**Comment by Fizzadar** [comment]
Excellent :) - was there system changes to get Kanmail to use the proxy? Would be good to add instructions to the docs!
